title:              Gaurav Joshi Blog
email:              gauravcjoshi17@gmail.com
description:        A blog about my journey through open source
author:             Gaurav Joshi
baseurl:            "/Blogs"
url:                "https://Gaurav17Joshi.github.io"

# Social Profiles
twitter_username:   
github_username:    Gaurav17Joshi
facebook_username:  
instagram_username:  
linkedin_username:  Gaurav Joshi

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
